version: "3.8"
services:
  db:
    image: postgres
    container_name: fastapi-boilerplate
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: pass123
        POSTGRES_DB: postgres
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"